name: unit-tests

on: [push]

jobs:
  unit-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: Invoke-WebRequest -Uri "https://github.com/OrbitalOwen/run-in-roblox/releases/download/0.2.0/run-in-roblox.exe" -OutFile run-in-roblox.exe
      - run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/OrbitalOwen/roblox-win-installer/master/install.py" -OutFile install.py
      - run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/OrbitalOwen/roblox-win-installer/master/GlobalSettings_13.xml" -OutFile GlobalSettings_13.xml
      - run: pip install wget psutil
      - run: python install.py "${{ secrets.ROBLOSECURITY }}"
      - name: install roblox-ts
        run: npm install roblox-ts
      - name: install foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install foreman packages (rojo)
        run: foreman install
      - name: build test place
        run: |
          rbxtsc
          rojo build -o .\\tests\\build.rbxlx tests
      - run: .\\run-in-roblox.exe tests\\build.rbxlx -t 1800 -s .\\tests\\spec.lua
